-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 10:56:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO_VALUE_SET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TIPO_VALUE_SET` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_VALUE_SET` (
  `ID_TIPO_VALUE_SET` INT NOT NULL AUTO_INCREMENT,
  `NOM_VALUE_SET` VARCHAR(255) NOT NULL,
  `NOM_VALUE_SET_FHIR` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_TIPO_VALUE_SET`));


-- -----------------------------------------------------
-- Table `mydb`.`VALUE_SET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VALUE_SET` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VALUE_SET` (
  `ID_VALOR` INT NOT NULL AUTO_INCREMENT,
  `ID_TIPO_VALUE_SET` INT NOT NULL,
  `CODE` VARCHAR(255) NOT NULL,
  `SYSTEM` VARCHAR(255) NOT NULL,
  `DISPLAY` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_VALOR`),
  INDEX `VALUE_SET_fk0` (`ID_TIPO_VALUE_SET` ASC) VISIBLE,
  CONSTRAINT `VALUE_SET_fk0`
    FOREIGN KEY (`ID_TIPO_VALUE_SET`)
    REFERENCES `mydb`.`TIPO_VALUE_SET` (`ID_TIPO_VALUE_SET`));


-- -----------------------------------------------------
-- Table `mydb`.`MEDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEDICO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEDICO` (
  `ID_MEDICO` INT NOT NULL AUTO_INCREMENT,
  `COD_RNPI` VARCHAR(255) NOT NULL,
  `NRO_RUT` VARCHAR(45) NULL,
  `DV_RUT` VARCHAR(1) NULL,
  `NOMBRES_MEDICO` VARCHAR(255) NULL,
  `APEPAT_MEDICO` VARCHAR(255) NULL,
  `APEMAT_MEDICO` VARCHAR(255) NULL,
  `COD_TITULO` VARCHAR(45) NULL,
  `NOM_USUARIO` VARCHAR(255) NULL,
  `PASS_USUARIO` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_MEDICO`));


-- -----------------------------------------------------
-- Table `mydb`.`CENTRO_ASISTENCIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CENTRO_ASISTENCIAL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CENTRO_ASISTENCIAL` (
  `ID_CENTRO` INT NOT NULL AUTO_INCREMENT,
  `COD_DEIS_CENTRO` VARCHAR(45) NULL,
  `NOM_CENTRO` VARCHAR(255) NULL,
  `COD_REGION_CODEVS` VARCHAR(45) NULL,
  `NIVEL_ATENCION` VARCHAR(255) NULL,
  `COD_COMUNA_CODEVS` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_CENTRO`));


-- -----------------------------------------------------
-- Table `mydb`.`CAT_DIAGNOSTICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CAT_DIAGNOSTICO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CAT_DIAGNOSTICO` (
  `ID_CAT_DIAG` INT NOT NULL,
  `NOM_CAT_DIAG` VARCHAR(255) NULL,
  `CODE_DIAG` VARCHAR(255) NULL,
  `SYSTEM_DIAG` VARCHAR(255) NULL,
  `DISPLAY_DIAG` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_CAT_DIAG`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
