DELETE FROM mydb.VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 1;
COMMIT;

DELETE FROM mydb.TIPO_VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 1;
COMMIT;

INSERT INTO mydb.TIPO_VALUE_SET(ID_TIPO_VALUE_SET, NOM_VALUE_SET, NOM_VALUE_SET_FHIR) VALUES(1, 'PAISES', 'PAISES');
COMMIT;

INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (1,1,REPLACE('  004', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Afghanistan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (2,1,REPLACE('  008', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Albania');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (3,1,REPLACE('  010', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Antarctica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (4,1,REPLACE('  012', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Algeria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (5,1,REPLACE('  016', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','American Samoa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (6,1,REPLACE('  020', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Andorra');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (7,1,REPLACE('  024', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Angola');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (8,1,REPLACE('  028', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Antigua and Barbuda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (9,1,REPLACE('  031', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Azerbaijan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (10,1,REPLACE('  032', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Argentina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (11,1,REPLACE('  036', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Australia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (12,1,REPLACE('  040', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Austria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (13,1,REPLACE('  044', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bahamas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (14,1,REPLACE('  048', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bahrain');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (15,1,REPLACE('  050', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bangladesh');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (16,1,REPLACE('  051', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Armenia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (17,1,REPLACE('  052', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Barbados');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (18,1,REPLACE('  056', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Belgium');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (19,1,REPLACE('  060', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bermuda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (20,1,REPLACE('  064', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bhutan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (21,1,REPLACE('  068', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bolivia, Plurinational State of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (22,1,REPLACE('  070', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bosnia and Herzegovina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (23,1,REPLACE('  072', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Botswana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (24,1,REPLACE('  074', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bouvet Island');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (25,1,REPLACE('  076', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Brazil');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (26,1,REPLACE('  084', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Belize');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (27,1,REPLACE('  086', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','British Indian Ocean Territory');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (28,1,REPLACE('  090', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Solomon Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (29,1,REPLACE('  092', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Virgin Islands, British');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (30,1,REPLACE('  096', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Brunei Darussalam');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (31,1,REPLACE('  100', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bulgaria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (32,1,REPLACE('  104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Myanmar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (33,1,REPLACE('  108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Burundi');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (34,1,REPLACE('  112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Belarus');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (35,1,REPLACE('  116', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cambodia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (36,1,REPLACE('  120', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cameroon');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (37,1,REPLACE('  124', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Canada');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (38,1,REPLACE('  132', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cabo Verde');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (39,1,REPLACE('  136', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cayman Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (40,1,REPLACE('  140', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Central African Republic');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (41,1,REPLACE('  144', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sri Lanka');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (42,1,REPLACE('  148', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Chad');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (43,1,REPLACE('  152', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Chile');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (44,1,REPLACE('  156', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','China');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (45,1,REPLACE('  158', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Taiwan, Province of China');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (46,1,REPLACE('  162', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Christmas Island');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (47,1,REPLACE('  166', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cocos (Keeling) Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (48,1,REPLACE('  170', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Colombia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (49,1,REPLACE('  174', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Comoros');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (50,1,REPLACE('  175', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mayotte');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (51,1,REPLACE('  178', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Congo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (52,1,REPLACE('  180', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Congo, the Democratic Republic of the');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (53,1,REPLACE('  184', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cook Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (54,1,REPLACE('  188', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Costa Rica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (55,1,REPLACE('  191', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Croatia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (56,1,REPLACE('  192', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cuba');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (57,1,REPLACE('  196', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Cyprus');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (58,1,REPLACE('  203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Czechia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (59,1,REPLACE('  204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Benin');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (60,1,REPLACE('  208', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Denmark');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (61,1,REPLACE('  212', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Dominica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (62,1,REPLACE('  214', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Dominican Republic');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (63,1,REPLACE('  218', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ecuador');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (64,1,REPLACE('  222', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','El Salvador');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (65,1,REPLACE('  226', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Equatorial Guinea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (66,1,REPLACE('  231', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ethiopia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (67,1,REPLACE('  232', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Eritrea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (68,1,REPLACE('  233', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Estonia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (69,1,REPLACE('  234', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Faroe Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (70,1,REPLACE('  238', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Falkland Islands (Malvinas)');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (71,1,REPLACE('  239', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','South Georgia and the South Sandwich Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (72,1,REPLACE('  242', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Fiji');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (73,1,REPLACE('  246', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Finland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (74,1,REPLACE('  248', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Eland Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (75,1,REPLACE('  250', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','France');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (76,1,REPLACE('  254', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','French Guiana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (77,1,REPLACE('  258', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','French Polynesia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (78,1,REPLACE('  260', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','French Southern Territories');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (79,1,REPLACE('  262', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Djibouti');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (80,1,REPLACE('  266', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Gabon');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (81,1,REPLACE('  268', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Georgia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (82,1,REPLACE('  270', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Gambia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (83,1,REPLACE('  275', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Palestine, State of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (84,1,REPLACE('  276', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Germany');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (85,1,REPLACE('  288', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ghana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (86,1,REPLACE('  292', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Gibraltar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (87,1,REPLACE('  296', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Kiribati');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (88,1,REPLACE('  300', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Greece');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (89,1,REPLACE('  304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Greenland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (90,1,REPLACE('  308', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Grenada');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (91,1,REPLACE('  312', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guadeloupe');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (92,1,REPLACE('  316', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guam');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (93,1,REPLACE('  320', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guatemala');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (94,1,REPLACE('  324', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guinea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (95,1,REPLACE('  328', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guyana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (96,1,REPLACE('  332', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Haiti');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (97,1,REPLACE('  334', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Heard Island and McDonald Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (98,1,REPLACE('  336', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Holy See');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (99,1,REPLACE('  340', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Honduras');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (100,1,REPLACE('  344', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Hong Kong');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (101,1,REPLACE('  348', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Hungary');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (102,1,REPLACE('  352', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Iceland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (103,1,REPLACE('  356', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','India');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (104,1,REPLACE('  360', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Indonesia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (105,1,REPLACE('  364', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Iran, Islamic Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (106,1,REPLACE('  368', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Iraq');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (107,1,REPLACE('  372', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ireland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (108,1,REPLACE('  376', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Israel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (109,1,REPLACE('  380', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Italy');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (110,1,REPLACE('  384', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ctte d\'Ivoire');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (111,1,REPLACE('  388', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Jamaica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (112,1,REPLACE('  392', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Japan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (113,1,REPLACE('  398', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Kazakhstan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (114,1,REPLACE('  400', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Jordan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (115,1,REPLACE('  404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Kenya');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (116,1,REPLACE('  408', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Korea, Democratic People\'s Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (117,1,REPLACE('  410', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Korea, Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (118,1,REPLACE('  414', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Kuwait');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (119,1,REPLACE('  417', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Kyrgyzstan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (120,1,REPLACE('  418', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Lao People\'s Democratic Republic');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (121,1,REPLACE('  422', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Lebanon');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (122,1,REPLACE('  426', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Lesotho');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (123,1,REPLACE('  428', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Latvia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (124,1,REPLACE('  430', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Liberia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (125,1,REPLACE('  434', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Libya');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (126,1,REPLACE('  438', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Liechtenstein');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (127,1,REPLACE('  440', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Lithuania');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (128,1,REPLACE('  442', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Luxembourg');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (129,1,REPLACE('  446', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Macao');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (130,1,REPLACE('  450', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Madagascar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (131,1,REPLACE('  454', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Malawi');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (132,1,REPLACE('  458', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Malaysia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (133,1,REPLACE('  462', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Maldives');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (134,1,REPLACE('  466', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mali');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (135,1,REPLACE('  470', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Malta');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (136,1,REPLACE('  474', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Martinique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (137,1,REPLACE('  478', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mauritania');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (138,1,REPLACE('  480', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mauritius');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (139,1,REPLACE('  484', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mexico');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (140,1,REPLACE('  492', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Monaco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (141,1,REPLACE('  496', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mongolia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (142,1,REPLACE('  498', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Moldova, Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (143,1,REPLACE('  499', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Montenegro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (144,1,REPLACE('  500', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Montserrat');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (145,1,REPLACE('  504', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Morocco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (146,1,REPLACE('  508', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Mozambique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (147,1,REPLACE('  512', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Oman');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (148,1,REPLACE('  516', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Namibia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (149,1,REPLACE('  520', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Nauru');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (150,1,REPLACE('  524', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Nepal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (151,1,REPLACE('  528', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Netherlands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (152,1,REPLACE('  531', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Curagao');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (153,1,REPLACE('  533', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Aruba');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (154,1,REPLACE('  534', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sint Maarten (Dutch part)');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (155,1,REPLACE('  535', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Bonaire, Sint Eustatius and Saba');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (156,1,REPLACE('  540', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','New Caledonia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (157,1,REPLACE('  548', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Vanuatu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (158,1,REPLACE('  554', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','New Zealand');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (159,1,REPLACE('  558', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Nicaragua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (160,1,REPLACE('  562', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Niger');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (161,1,REPLACE('  566', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Nigeria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (162,1,REPLACE('  570', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Niue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (163,1,REPLACE('  574', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Norfolk Island');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (164,1,REPLACE('  578', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Norway');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (165,1,REPLACE('  580', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Northern Mariana Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (166,1,REPLACE('  581', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','United States Minor Outlying Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (167,1,REPLACE('  583', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Micronesia, Federated States of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (168,1,REPLACE('  584', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Marshall Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (169,1,REPLACE('  585', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Palau');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (170,1,REPLACE('  586', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Pakistan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (171,1,REPLACE('  591', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Panama');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (172,1,REPLACE('  598', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Papua New Guinea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (173,1,REPLACE('  600', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Paraguay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (174,1,REPLACE('  604', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Peru');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (175,1,REPLACE('  608', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Philippines');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (176,1,REPLACE('  612', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Pitcairn');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (177,1,REPLACE('  616', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Poland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (178,1,REPLACE('  620', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Portugal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (179,1,REPLACE('  624', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guinea-Bissau');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (180,1,REPLACE('  626', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Timor-Leste');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (181,1,REPLACE('  630', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Puerto Rico');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (182,1,REPLACE('  634', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Qatar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (183,1,REPLACE('  638', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Riunion');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (184,1,REPLACE('  642', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Romania');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (185,1,REPLACE('  643', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Russian Federation');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (186,1,REPLACE('  646', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Rwanda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (187,1,REPLACE('  652', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Barthilemy');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (188,1,REPLACE('  654', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (189,1,REPLACE('  659', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Kitts and Nevis');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (190,1,REPLACE('  660', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Anguilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (191,1,REPLACE('  662', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Lucia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (192,1,REPLACE('  663', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Martin (French part)');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (193,1,REPLACE('  666', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Pierre and Miquelon');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (194,1,REPLACE('  670', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saint Vincent and the Grenadines');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (195,1,REPLACE('  674', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','San Marino');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (196,1,REPLACE('  678', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sao Tome and Principe');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (197,1,REPLACE('  682', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Saudi Arabia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (198,1,REPLACE('  686', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Senegal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (199,1,REPLACE('  688', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Serbia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (200,1,REPLACE('  690', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Seychelles');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (201,1,REPLACE('  694', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sierra Leone');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (202,1,REPLACE('  702', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Singapore');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (203,1,REPLACE('  703', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Slovakia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (204,1,REPLACE('  704', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Viet Nam');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (205,1,REPLACE('  705', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Slovenia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (206,1,REPLACE('  706', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Somalia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (207,1,REPLACE('  710', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','South Africa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (208,1,REPLACE('  716', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Zimbabwe');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (209,1,REPLACE('  724', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Spain');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (210,1,REPLACE('  728', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','South Sudan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (211,1,REPLACE('  729', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sudan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (212,1,REPLACE('  732', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Western Sahara');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (213,1,REPLACE('  740', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Suriname');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (214,1,REPLACE('  744', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Svalbard and Jan Mayen');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (215,1,REPLACE('  748', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Swaziland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (216,1,REPLACE('  752', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Sweden');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (217,1,REPLACE('  756', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Switzerland');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (218,1,REPLACE('  760', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Syrian Arab Republic');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (219,1,REPLACE('  762', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tajikistan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (220,1,REPLACE('  764', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Thailand');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (221,1,REPLACE('  768', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Togo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (222,1,REPLACE('  772', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tokelau');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (223,1,REPLACE('  776', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tonga');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (224,1,REPLACE('  780', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Trinidad and Tobago');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (225,1,REPLACE('  784', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','United Arab Emirates');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (226,1,REPLACE('  788', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tunisia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (227,1,REPLACE('  792', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Turkey');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (228,1,REPLACE('  795', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Turkmenistan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (229,1,REPLACE('  796', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Turks and Caicos Islands');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (230,1,REPLACE('  798', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tuvalu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (231,1,REPLACE('  800', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Uganda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (232,1,REPLACE('  804', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Ukraine');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (233,1,REPLACE('  807', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Macedonia, the former Yugoslav Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (234,1,REPLACE('  818', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Egypt');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (235,1,REPLACE('  826', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','United Kingdom');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (236,1,REPLACE('  831', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Guernsey');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (237,1,REPLACE('  832', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Jersey');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (238,1,REPLACE('  833', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Isle of Man');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (239,1,REPLACE('  834', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Tanzania, United Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (240,1,REPLACE('  840', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','United States of America');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (241,1,REPLACE('  850', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Virgin Islands, U.S.');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (242,1,REPLACE('  854', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Burkina Faso');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (243,1,REPLACE('  858', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Uruguay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (244,1,REPLACE('  860', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Uzbekistan');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (245,1,REPLACE('  862', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Venezuela, Bolivarian Republic of');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (246,1,REPLACE('  876', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Wallis and Futuna');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (247,1,REPLACE('  882', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Samoa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (248,1,REPLACE('  887', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Yemen');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (249,1,REPLACE('  894', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais','Zambia');
COMMIT;