DELETE FROM mydb.VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 3;
COMMIT;

DELETE FROM mydb.TIPO_VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 3;
COMMIT;

INSERT INTO mydb.TIPO_VALUE_SET(ID_TIPO_VALUE_SET, NOM_VALUE_SET, NOM_VALUE_SET_FHIR) VALUES(3, 'PROVINCIAS', 'PROVINCIAS');
COMMIT;

INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (266,3,REPLACE('  122', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Antártica Chilena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (267,3,REPLACE('  021', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Antofagasta');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (268,3,REPLACE('  082', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Arauco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (269,3,REPLACE('  151', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Arica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (270,3,REPLACE('  112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Aysén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (271,3,REPLACE('  083', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Biobío');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (272,3,REPLACE('  061', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Cachapoal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (273,3,REPLACE('  113', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Capitán Prat');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (274,3,REPLACE('  062', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Cardenal Caro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (275,3,REPLACE('  072', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Cauquenes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (276,3,REPLACE('  091', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Cautín');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (277,3,REPLACE('  133', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Chacabuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (278,3,REPLACE('  032', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Chañaral');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (279,3,REPLACE('  102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Chiloé');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (280,3,REPLACE('  042', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Choapa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (281,3,REPLACE('  111', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Coihaique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (282,3,REPLACE('  063', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Colchagua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (283,3,REPLACE('  081', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Concepción');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (284,3,REPLACE('  031', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Copiapó');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (285,3,REPLACE('  132', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Cordillera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (286,3,REPLACE('  073', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Curicó');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (287,3,REPLACE('  161', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Diguillín');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (288,3,REPLACE('  022', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','El Loa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (289,3,REPLACE('  041', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Elqui');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (290,3,REPLACE('  114', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','General Carrera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (291,3,REPLACE('  033', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Huasco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (292,3,REPLACE('  011', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Iquique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (293,3,REPLACE('  052', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Isla de Pascua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (294,3,REPLACE('  162', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Itata');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (295,3,REPLACE('  043', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Limarí');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (296,3,REPLACE('  074', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Linares');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (297,3,REPLACE('  101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Llanquihue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (298,3,REPLACE('  053', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Los Andes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (299,3,REPLACE('  121', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Magallanes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (300,3,REPLACE('  134', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Maipo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (301,3,REPLACE('  092', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Malleco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (302,3,REPLACE('  058', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Marga Marga');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (303,3,REPLACE('  135', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Melipilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (304,3,REPLACE('  103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Osorno');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (305,3,REPLACE('  104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Palena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (306,3,REPLACE('  152', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Parinacota');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (307,3,REPLACE('  054', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Petorca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (308,3,REPLACE('  163', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Punilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (309,3,REPLACE('  055', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Quillota');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (310,3,REPLACE('  142', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Ranco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (311,3,REPLACE('  056', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','San Antonio');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (312,3,REPLACE('  057', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','San Felipe de Aconcagua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (313,3,REPLACE('  131', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Santiago');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (314,3,REPLACE('  136', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Talagante');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (315,3,REPLACE('  071', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Talca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (316,3,REPLACE('  014', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Tamarugal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (317,3,REPLACE('  123', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Tierra del Fuego');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (318,3,REPLACE('  023', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Tocopilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (319,3,REPLACE('  124', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','última Esperanza');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (320,3,REPLACE('  141', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Valdivia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (321,3,REPLACE('  051', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL','Valparaíso');
COMMIT;