DELETE FROM mydb.VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 4;
COMMIT;

DELETE FROM mydb.TIPO_VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 4;
COMMIT;

INSERT INTO mydb.TIPO_VALUE_SET(ID_TIPO_VALUE_SET, NOM_VALUE_SET, NOM_VALUE_SET_FHIR) VALUES(4, 'COMUNAS', 'COMUNAS');
COMMIT;

INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (322,4,REPLACE('  05602', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Algarrobo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (323,4,REPLACE('  13502', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Alhué');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (324,4,REPLACE('  08314', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Alto Biobío');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (325,4,REPLACE('  03302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Alto del Carmen');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (326,4,REPLACE('  01107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Alto Hospicio');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (327,4,REPLACE('  10202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ancud');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (328,4,REPLACE('  04103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Andacollo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (329,4,REPLACE('  09201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Angol');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (330,4,REPLACE('  12202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Antartica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (331,4,REPLACE('  02101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Antofagasta');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (332,4,REPLACE('  08302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Antuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (333,4,REPLACE('  08202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Arauco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (334,4,REPLACE('  15101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Arica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (335,4,REPLACE('  11201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Aysén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (336,4,REPLACE('  13402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Buin');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (337,4,REPLACE('  16102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Bulnes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (338,4,REPLACE('  05402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cabildo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (339,4,REPLACE('  12201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cabo de Hornos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (340,4,REPLACE('  08303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cabrero');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (341,4,REPLACE('  02201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Calama');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (342,4,REPLACE('  10102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Calbuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (343,4,REPLACE('  03102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Caldera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (344,4,REPLACE('  05502', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Calera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (345,4,REPLACE('  13403', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Calera de Tango');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (346,4,REPLACE('  05302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Calle Larga');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (347,4,REPLACE('  15102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Camarones');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (348,4,REPLACE('  01402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Camiña');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (349,4,REPLACE('  04202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Canela');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (350,4,REPLACE('  08203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cañete');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (351,4,REPLACE('  09102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Carahue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (352,4,REPLACE('  05603', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cartagena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (353,4,REPLACE('  05102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Casablanca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (354,4,REPLACE('  10201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Castro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (355,4,REPLACE('  05702', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Catemu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (356,4,REPLACE('  07201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cauquenes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (357,4,REPLACE('  13102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cerrillos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (358,4,REPLACE('  13103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cerro Navia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (359,4,REPLACE('  10401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chaitén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (360,4,REPLACE('  03201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chañaral');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (361,4,REPLACE('  07202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chanco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (362,4,REPLACE('  06302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chépica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (363,4,REPLACE('  08103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chiguayante');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (364,4,REPLACE('  11401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chile Chico');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (365,4,REPLACE('  16101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chillán');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (366,4,REPLACE('  16103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chillán Viejo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (367,4,REPLACE('  06303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chimbarongo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (368,4,REPLACE('  09121', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cholchol');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (369,4,REPLACE('  10203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Chonchi');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (370,4,REPLACE('  11202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cisnes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (371,4,REPLACE('  16202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cobquecura');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (372,4,REPLACE('  10103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cochamó');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (373,4,REPLACE('  11301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cochrane');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (374,4,REPLACE('  06102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Codegua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (375,4,REPLACE('  16203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coelemu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (376,4,REPLACE('  11101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coihaique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (377,4,REPLACE('  16302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coihueco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (378,4,REPLACE('  06103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coinco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (379,4,REPLACE('  07402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Colbún');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (380,4,REPLACE('  01403', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Colchane');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (381,4,REPLACE('  13301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Colina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (382,4,REPLACE('  09202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Collipulli');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (383,4,REPLACE('  06104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coltauco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (384,4,REPLACE('  04302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Combarbalá');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (385,4,REPLACE('  08101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Concepción');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (386,4,REPLACE('  13104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Conchalí');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (387,4,REPLACE('  05103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Concón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (388,4,REPLACE('  07102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Constitución');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (389,4,REPLACE('  08204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Contulmo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (390,4,REPLACE('  03101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Copiapó');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (391,4,REPLACE('  04102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coquimbo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (392,4,REPLACE('  08102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Coronel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (393,4,REPLACE('  14102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Corral');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (394,4,REPLACE('  09103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Cunco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (395,4,REPLACE('  09203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curacautín');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (396,4,REPLACE('  13503', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curacaví');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (397,4,REPLACE('  10204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curaco de Vélez');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (398,4,REPLACE('  08205', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curanilahue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (399,4,REPLACE('  09104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curarrehue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (400,4,REPLACE('  07103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curepto');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (401,4,REPLACE('  07301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Curicó');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (402,4,REPLACE('  10205', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Dalcahue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (403,4,REPLACE('  03202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Diego de Almagro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (404,4,REPLACE('  06105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Doñihue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (405,4,REPLACE('  13105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','El Bosque');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (406,4,REPLACE('  16104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','El Carmen');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (407,4,REPLACE('  13602', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','El Monte');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (408,4,REPLACE('  05604', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','El Quisco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (409,4,REPLACE('  05605', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','El Tabo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (410,4,REPLACE('  07104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Empedrado');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (411,4,REPLACE('  09204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ercilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (412,4,REPLACE('  13106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Estacin Central');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (413,4,REPLACE('  08104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Florida');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (414,4,REPLACE('  09105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Freire');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (415,4,REPLACE('  03303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Freirina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (416,4,REPLACE('  10104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Fresia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (417,4,REPLACE('  10105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Frutillar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (418,4,REPLACE('  10402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Futaleufú');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (419,4,REPLACE('  14202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Futrono');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (420,4,REPLACE('  09106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Galvarino');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (421,4,REPLACE('  15202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','General Lagos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (422,4,REPLACE('  09107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Gorbea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (423,4,REPLACE('  06106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Graneros');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (424,4,REPLACE('  11203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Guaitecas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (425,4,REPLACE('  05503', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Hijuelas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (426,4,REPLACE('  10403', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Hualaihué');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (427,4,REPLACE('  07302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Hualañé');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (428,4,REPLACE('  08112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Hualpén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (429,4,REPLACE('  08105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Hualqui');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (430,4,REPLACE('  01404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Huara');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (431,4,REPLACE('  03304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Huasco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (432,4,REPLACE('  13107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Huechuraba');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (433,4,REPLACE('  04201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Illapel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (434,4,REPLACE('  13108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Independencia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (435,4,REPLACE('  01101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Iquique');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (436,4,REPLACE('  13603', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Isla de Maipo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (437,4,REPLACE('  05201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Isla de Pascua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (438,4,REPLACE('  05104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Juan Fernández');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (439,4,REPLACE('  13109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Cisterna');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (440,4,REPLACE('  05504', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Cruz');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (441,4,REPLACE('  06202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Estrella');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (442,4,REPLACE('  13110', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Florida');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (443,4,REPLACE('  13111', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Granja');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (444,4,REPLACE('  04104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Higuera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (445,4,REPLACE('  05401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Ligua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (446,4,REPLACE('  13112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Pintana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (447,4,REPLACE('  13113', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Reina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (448,4,REPLACE('  04101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Serena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (449,4,REPLACE('  14201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','La Unión');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (450,4,REPLACE('  14203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lago Ranco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (451,4,REPLACE('  11102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lago Verde');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (452,4,REPLACE('  12102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Laguna Blanca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (453,4,REPLACE('  08304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Laja');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (454,4,REPLACE('  13302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lampa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (455,4,REPLACE('  14103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lanco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (456,4,REPLACE('  06107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Las Cabras');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (457,4,REPLACE('  13114', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Las Condes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (458,4,REPLACE('  09108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lautaro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (459,4,REPLACE('  08201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lebu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (460,4,REPLACE('  07303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Licantén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (461,4,REPLACE('  05802', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Limache');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (462,4,REPLACE('  07401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Linares');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (463,4,REPLACE('  06203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Litueche');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (464,4,REPLACE('  05703', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Llaillay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (465,4,REPLACE('  10107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Llanquihue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (466,4,REPLACE('  13115', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lo Barnechea');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (467,4,REPLACE('  13116', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lo Espejo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (468,4,REPLACE('  13117', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lo Prado');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (469,4,REPLACE('  06304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lolol');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (470,4,REPLACE('  09109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Loncoche');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (471,4,REPLACE('  07403', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Longaví');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (472,4,REPLACE('  09205', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lonquimay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (473,4,REPLACE('  08206', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Álamos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (474,4,REPLACE('  05301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Andes');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (475,4,REPLACE('  08301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Ángeles');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (476,4,REPLACE('  14104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Lagos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (477,4,REPLACE('  10106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Muermos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (478,4,REPLACE('  09206', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Sauces');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (479,4,REPLACE('  04203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Los Vilos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (480,4,REPLACE('  08106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lota');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (481,4,REPLACE('  09207', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Lumaco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (482,4,REPLACE('  06108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Machalí');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (483,4,REPLACE('  13118', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Macul');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (484,4,REPLACE('  14105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Máfil');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (485,4,REPLACE('  13119', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Maipú');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (486,4,REPLACE('  06109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Malloa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (487,4,REPLACE('  06204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Marchihue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (488,4,REPLACE('  02302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','María Elena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (489,4,REPLACE('  13504', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','María Pinto');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (490,4,REPLACE('  14106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Mariquina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (491,4,REPLACE('  07105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Maule');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (492,4,REPLACE('  10108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Maullín');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (493,4,REPLACE('  02102', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Mejillones');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (494,4,REPLACE('  09110', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Melipeuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (495,4,REPLACE('  13501', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Melipilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (496,4,REPLACE('  07304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Molina');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (497,4,REPLACE('  04303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Monte Patria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (498,4,REPLACE('  06110', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Mostazal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (499,4,REPLACE('  08305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Mulchén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (500,4,REPLACE('  08306', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Nacimiento');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (501,4,REPLACE('  06305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Nancagua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (502,4,REPLACE('  12401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Natales');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (503,4,REPLACE('  06205', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Navidad');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (504,4,REPLACE('  08307', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Negrete');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (505,4,REPLACE('  16204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ninhue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (506,4,REPLACE('  16303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ñiquén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (507,4,REPLACE('  05506', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Nogales');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (508,4,REPLACE('  09111', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Nueva Imperial');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (509,4,REPLACE('  13120', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','ÑuÑoa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (510,4,REPLACE('  06111', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Olivar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (511,4,REPLACE('  02202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ollagüe');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (512,4,REPLACE('  05803', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Olmué');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (513,4,REPLACE('  10301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Osorno');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (514,4,REPLACE('  04301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ovalle');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (515,4,REPLACE('  11302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','O\'Higgins');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (516,4,REPLACE('  13604', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Padre Hurtado');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (517,4,REPLACE('  09112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Padre las Casas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (518,4,REPLACE('  04105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Paiguano');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (519,4,REPLACE('  14107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Paillaco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (520,4,REPLACE('  13404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Paine');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (521,4,REPLACE('  10404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Palena');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (522,4,REPLACE('  06306', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Palmilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (523,4,REPLACE('  14108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Panguipulli');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (524,4,REPLACE('  05704', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Panquehue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (525,4,REPLACE('  05403', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Papudo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (526,4,REPLACE('  06206', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Paredones');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (527,4,REPLACE('  07404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Parral');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (528,4,REPLACE('  13121', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pedro Aguirre Cerda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (529,4,REPLACE('  07106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pelarco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (530,4,REPLACE('  07203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pelluhue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (531,4,REPLACE('  16105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pemuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (532,4,REPLACE('  13605', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Peñaflor');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (533,4,REPLACE('  13122', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Peñalolén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (534,4,REPLACE('  07107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pencahue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (535,4,REPLACE('  08107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Penco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (536,4,REPLACE('  06307', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Peralillo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (537,4,REPLACE('  09113', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Perquenco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (538,4,REPLACE('  05404', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Petorca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (539,4,REPLACE('  06112', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Peumo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (540,4,REPLACE('  01405', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (541,4,REPLACE('  06113', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pichidegua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (542,4,REPLACE('  06201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pichilemu');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (543,4,REPLACE('  16106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pinto');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (544,4,REPLACE('  13202', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pirque');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (545,4,REPLACE('  09114', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pitrufquén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (546,4,REPLACE('  06308', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Placilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (547,4,REPLACE('  16205', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Portezuelo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (548,4,REPLACE('  12301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Porvenir');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (549,4,REPLACE('  01401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pozo Almonte');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (550,4,REPLACE('  12302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Primavera');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (551,4,REPLACE('  13123', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Providencia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (552,4,REPLACE('  05105', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puchuncaví');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (553,4,REPLACE('  09115', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pucón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (554,4,REPLACE('  13124', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pudahuel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (555,4,REPLACE('  13201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puente Alto');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (556,4,REPLACE('  10101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puerto Montt');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (557,4,REPLACE('  10302', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puerto Octay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (558,4,REPLACE('  10109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puerto Varas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (559,4,REPLACE('  06309', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Pumanque');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (560,4,REPLACE('  04304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Punitaqui');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (561,4,REPLACE('  12101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Punta Arenas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (562,4,REPLACE('  10206', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puqueldón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (563,4,REPLACE('  09208', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Purén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (564,4,REPLACE('  10303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Purranque');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (565,4,REPLACE('  05705', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Putaendo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (566,4,REPLACE('  15201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Putre');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (567,4,REPLACE('  10304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Puyehue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (568,4,REPLACE('  10207', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Queilén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (569,4,REPLACE('  10208', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quellón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (570,4,REPLACE('  10209', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quemchi');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (571,4,REPLACE('  08308', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quilaco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (572,4,REPLACE('  13125', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quilicura');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (573,4,REPLACE('  08309', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quilleco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (574,4,REPLACE('  16107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quillón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (575,4,REPLACE('  05501', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quillota');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (576,4,REPLACE('  05801', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quilpué');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (577,4,REPLACE('  10210', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quinchao');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (578,4,REPLACE('  06114', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quinta de Tilcoco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (579,4,REPLACE('  13126', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quinta Normal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (580,4,REPLACE('  05107', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quintero');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (581,4,REPLACE('  16201', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Quirihue');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (582,4,REPLACE('  06101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Rancagua');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (583,4,REPLACE('  16206', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Ránquil');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (584,4,REPLACE('  07305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Rauco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (585,4,REPLACE('  13127', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Recoleta');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (586,4,REPLACE('  09209', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Renaico');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (587,4,REPLACE('  13128', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Renca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (588,4,REPLACE('  06115', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Rengo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (589,4,REPLACE('  06116', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Requínoa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (590,4,REPLACE('  07405', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Retiro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (591,4,REPLACE('  05303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Rinconada');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (592,4,REPLACE('  14204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Bueno');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (593,4,REPLACE('  07108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Claro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (594,4,REPLACE('  04305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Hurtado');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (595,4,REPLACE('  11402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Ibáñez');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (596,4,REPLACE('  10305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Negro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (597,4,REPLACE('  12103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Río Verde');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (598,4,REPLACE('  07306', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Romeral');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (599,4,REPLACE('  09116', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Saavedra');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (600,4,REPLACE('  07307', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Sagrada Familia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (601,4,REPLACE('  04204', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Salamanca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (602,4,REPLACE('  05601', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Antonio');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (603,4,REPLACE('  13401', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Bernardo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (604,4,REPLACE('  16301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Carlos');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (605,4,REPLACE('  07109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Clemente');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (606,4,REPLACE('  05304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Esteban');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (607,4,REPLACE('  16304', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Fabián');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (608,4,REPLACE('  05701', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Felipe');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (609,4,REPLACE('  06301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Fernando');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (610,4,REPLACE('  12104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Gregorio');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (611,4,REPLACE('  16108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Ignacio');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (612,4,REPLACE('  07406', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Javier');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (613,4,REPLACE('  13129', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Joaquín');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (614,4,REPLACE('  13203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San José de Maipo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (615,4,REPLACE('  10306', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Juan de la Costa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (616,4,REPLACE('  13130', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Miguel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (617,4,REPLACE('  16305', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Nicolás');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (618,4,REPLACE('  10307', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Pablo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (619,4,REPLACE('  13505', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Pedro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (620,4,REPLACE('  02203', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Pedro de Atacama');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (621,4,REPLACE('  08108', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Pedro de la Paz');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (622,4,REPLACE('  07110', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Rafael');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (623,4,REPLACE('  13131', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Ramón');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (624,4,REPLACE('  08310', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Rosendo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (625,4,REPLACE('  06117', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','San Vicente');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (626,4,REPLACE('  08311', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santa Bárbara');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (627,4,REPLACE('  06310', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santa Cruz');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (628,4,REPLACE('  08109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santa Juana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (629,4,REPLACE('  05706', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santa María');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (630,4,REPLACE('  13101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santiago Centro');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (631,4,REPLACE('  05606', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Santo Domingo');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (632,4,REPLACE('  02103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Sierra Gorda');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (633,4,REPLACE('  13601', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Talagante');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (634,4,REPLACE('  07101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Talca');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (635,4,REPLACE('  08110', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Talcahuano');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (636,4,REPLACE('  02104', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Taltal');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (637,4,REPLACE('  09101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Temuco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (638,4,REPLACE('  07308', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Teno');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (639,4,REPLACE('  09117', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Teodoro Schmidt');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (640,4,REPLACE('  03103', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tierra Amarilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (641,4,REPLACE('  13303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tiltil');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (642,4,REPLACE('  12303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Timaukel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (643,4,REPLACE('  08207', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tirúa');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (644,4,REPLACE('  02301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tocopilla');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (645,4,REPLACE('  09118', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Toltén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (646,4,REPLACE('  08111', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tomé');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (647,4,REPLACE('  12402', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Torres del Paine');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (648,4,REPLACE('  11303', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tortel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (649,4,REPLACE('  09210', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Traiguén');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (650,4,REPLACE('  16207', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Treguaco');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (651,4,REPLACE('  08312', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Tucapel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (652,4,REPLACE('  14101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Valdivia');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (653,4,REPLACE('  03301', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Vallenar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (654,4,REPLACE('  05101', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Valparaíso');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (655,4,REPLACE('  07309', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Vichuqué');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (656,4,REPLACE('  09211', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Victoria');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (657,4,REPLACE('  04106', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Vicuña');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (658,4,REPLACE('  09119', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Vilcún');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (659,4,REPLACE('  07407', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Villa Alegre');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (660,4,REPLACE('  05804', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Villa Alemana');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (661,4,REPLACE('  09120', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Villarrica');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (662,4,REPLACE('  05109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Viña del Mar');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (663,4,REPLACE('  13132', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Vitacura');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (664,4,REPLACE('  07408', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Yerbas Buenas');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (665,4,REPLACE('  08313', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Yumbel');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (666,4,REPLACE('  16109', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Yungay');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (667,4,REPLACE('  05405', ' ', ''),'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL','Zapallar');
COMMIT;