DELETE FROM mydb.VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 8;
COMMIT;

DELETE FROM mydb.TIPO_VALUE_SET T WHERE T.ID_TIPO_VALUE_SET = 8;
COMMIT;

INSERT INTO mydb.TIPO_VALUE_SET(ID_TIPO_VALUE_SET, NOM_VALUE_SET, NOM_VALUE_SET_FHIR) VALUES(8, 'ADMINISTRATIVE GENDER', 'ADMINISTRATIVE GENDER');
COMMIT;

INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (771,8,REPLACE('male', ' ', ''),'http://hl7.org/fhir/administrative-gender','Male');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (772,8,REPLACE('female', ' ', ''),'http://hl7.org/fhir/administrative-gender','Female');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (773,8,REPLACE('other', ' ', ''),'http://hl7.org/fhir/administrative-gender','Other');
INSERT INTO mydb.VALUE_SET(ID_VALOR, ID_TIPO_VALUE_SET, CODE, `SYSTEM`, DISPLAY) VALUES (774,8,REPLACE('unknown', ' ', ''),'http://hl7.org/fhir/administrative-gender','Unknown');
COMMIT;